# This lets you choose a database to use.
database: "data.db"

# Configure the max levels for PLAYERS here.
max-level: 100

# Configure the max prestige
max-prestige: 100

# Configure how much xp and coins a mob will give
# <entity type>: <integer value>
# Entity listed here must be valid from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Not having the proper entity listed WILL cause errors
# Types should not be case-sensitive
mob-types:
  zombie:
    xp: 10
    coins: 2
  skeleton:
    xp: 20
    coins: 4
  spider:
    xp: 30
    coins: 2
  piglin_brute:
    xp: 50
    coins: 6
  zoglin:
    xp: 60
    coins: 10
  blaze:
    xp: 70
    coins: 10
  wither_skeleton:
    xp: 80
    coins: 20

boss-types:
  zombie:
    xp: 1000
    coins: 1000
  piglin_brute:
    xp: 2000
    coins: 2000
  blaze:
    xp: 3000
    coins: 3000
  wither_skeleton:
    xp: 4000
    coins: 4000
  warden:
    xp: 5000
    coins: 5000

# Multiplier for each difficulty type
# Difficulty: <integer value>
# To disable set all values to one
# This is a multiplier, meaning all values above for xp and coins will be MULTIPLIED; setting to 0 means players get nothing
EASY: 1
MEDIUM: 2
HARD: 3
INSANE: 4

# Unless you have a valid reason to change this, leave it to false.
debug: false