name: ZombieArena
main: me.Visionexe.ZombieArena.ZombieArena
version: 1.0
api-version: 1.20
depend: [Vault, WorldEdit, AnimatedScoreboard]
commands:
  zombiearena:
    description: Get help for ZombieArena plugin
    aliases: [z, za, arena]
